package bean;

// Generated 2013-5-18 21:27:28 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Blogclassify generated by hbm2java
 */
public class Blogclassify implements java.io.Serializable {

	private Integer classifyId;
	private Users users;
	private String name;
	private Set<Blogcontent> blogcontents = new HashSet<Blogcontent>(0);

	public Blogclassify() {
	}

	public Blogclassify(Users users, String name) {
		this.users = users;
		this.name = name;
	}

	public Blogclassify(Users users, String name, Set<Blogcontent> blogcontents) {
		this.users = users;
		this.name = name;
		this.blogcontents = blogcontents;
	}

	public Integer getClassifyId() {
		return this.classifyId;
	}

	public void setClassifyId(Integer classifyId) {
		this.classifyId = classifyId;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set<Blogcontent> getBlogcontents() {
		return this.blogcontents;
	}

	public void setBlogcontents(Set<Blogcontent> blogcontents) {
		this.blogcontents = blogcontents;
	}

}
